version: '3.7'

services:
  my-app:
    build: .
    image: devops:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-db:5432/swe304
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - my-db

  my-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: swe304
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

networks:
  my-app:
  my-db:
