apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - port: 8080
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  selector:
    matchLabels:
      app: devops
  replicas: 1
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops
          image: ahmetalicc/devops:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/Swe304"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"